test_scenarios = {
    '1': {'maxfico': 640, 'lock': 60, 'rate_structure': 'FIXED', 'price': 150000,
            'loan_amount': 150000, 'arm_type': '', 'io': '', 'institution': 'BOFA',
            'loan_type': 'VA', 'ltv': 100, 'property_type': '', 'state': 'AK', 'minfico': 640,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '2': {'maxfico': 690, 'lock': 30, 'rate_structure': 'FIXED', 'price': 210526,
            'loan_amount': 200000, 'arm_type': '', 'io': '', 'institution': 'COMPASS',
            'loan_type': 'VA', 'ltv': 95, 'property_type': '', 'state': 'AL', 'minfico': 690,
            'loan_term': 15, 'loan_purpose': 'REFI'},
    '3': {'maxfico': 710, 'lock': 45, 'rate_structure': 'ARM', 'price': 83333,
            'loan_amount': 75000, 'arm_type': '3-1', 'io': '', 'institution': 'PNC',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'AR', 'minfico': 710,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '4': {'maxfico': 745, 'lock': 60, 'rate_structure': 'ARM', 'price': 444444,
            'loan_amount': 400000, 'arm_type': '3-1', 'io': 1.0, 'institution': 'USBANK',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'AZ', 'minfico': 745,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '5': {'maxfico': 760, 'lock': 30, 'rate_structure': 'FIXED', 'price': 1125000,
            'loan_amount': 900000, 'arm_type': '', 'io': '', 'institution': 'UNBK',
            'loan_type': 'JUMBO', 'ltv': 80, 'property_type': '', 'state': 'CA', 'minfico': 760,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '6': {'maxfico': 740, 'lock': 45, 'rate_structure': 'FIXED', 'price': 411764,
            'loan_amount': 350000, 'arm_type': '', 'io': '', 'institution': 'PATELCO',
            'loan_type': 'CONF', 'ltv': 85, 'property_type': '', 'state': 'CA', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '7': {'maxfico': 780, 'lock': 60, 'rate_structure': 'FIXED', 'price': 2000000,
            'loan_amount': 1500000, 'arm_type': '', 'io': '', 'institution': 'FIRSTBANK',
            'loan_type': 'JUMBO', 'ltv': 75, 'property_type': '', 'state': 'CO', 'minfico': 780,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '8': {'maxfico': 715, 'lock': 30, 'rate_structure': 'ARM', 'price': 617647,
            'loan_amount': 525000, 'arm_type': '7-1', 'io': 1.0, 'institution': 'RBS',
            'loan_type': 'AGENCY', 'ltv': 85, 'property_type': '', 'state': 'CT', 'minfico': 715,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '9': {'maxfico': 660, 'lock': 45, 'rate_structure': 'FIXED', 'price': 631578,
            'loan_amount': 600000, 'arm_type': '', 'io': '', 'institution': 'QUICKEN',
            'loan_type': 'FHA-HB', 'ltv': 95, 'property_type': '', 'state': 'DC', 'minfico': 660,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '10': {'maxfico': 690, 'lock': 60, 'rate_structure': 'FIXED', 'price': 233333,
            'loan_amount': 175000, 'arm_type': '', 'io': '', 'institution': 'CAPITAL ONE',
            'loan_type': 'CONF', 'ltv': 75, 'property_type': '', 'state': 'DE', 'minfico': 690,
            'loan_term': 15, 'loan_purpose': 'REFI'},
    '11': {'maxfico': 780, 'lock': 30, 'rate_structure': 'FIXED', 'price': 305555,
            'loan_amount': 275000, 'arm_type': '', 'io': '', 'institution': 'KINECTA',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'FL', 'minfico': 780,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '12': {'maxfico': 800, 'lock': 45, 'rate_structure': 'ARM', 'price': 1000000,
            'loan_amount': 700000, 'arm_type': '3-1', 'io': '', 'institution': 'FIRST TECH FCU',
            'loan_type': 'JUMBO', 'ltv': 70, 'property_type': '', 'state': 'GA', 'minfico': 800,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '13': {'maxfico': 720, 'lock': 60, 'rate_structure': 'FIXED', 'price': 823529,
            'loan_amount': 700000, 'arm_type': '', 'io': '', 'institution': 'PNC',
            'loan_type': 'AGENCY', 'ltv': 85, 'property_type': '', 'state': 'HI', 'minfico': 720,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '14': {'maxfico': 680, 'lock': 30, 'rate_structure': 'ARM', 'price': 222222,
            'loan_amount': 200000, 'arm_type': '5-1', 'io': '', 'institution': '53RD',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'IA', 'minfico': 680,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '15': {'maxfico': 650, 'lock': 45, 'rate_structure': 'FIXED', 'price': 105263,
            'loan_amount': 100000, 'arm_type': '', 'io': '', 'institution': 'ZIONS',
            'loan_type': 'FHA', 'ltv': 95, 'property_type': '', 'state': 'ID', 'minfico': 650,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '16': {'maxfico': 690, 'lock': 60, 'rate_structure': 'FIXED', 'price': 750000,
            'loan_amount': 600000, 'arm_type': '', 'io': '', 'institution': 'ASTORIA',
            'loan_type': 'AGENCY', 'ltv': 80, 'property_type': 'CONDO', 'state': 'IL', 'minfico': 690,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '17': {'maxfico': 710, 'lock': 30, 'rate_structure': 'FIXED', 'price': 157894,
            'loan_amount': 150000, 'arm_type': '', 'io': '', 'institution': 'CITI',
            'loan_type': 'FHA', 'ltv': 95, 'property_type': '', 'state': 'IN', 'minfico': 710,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '18': {'maxfico': 760, 'lock': 45, 'rate_structure': 'FIXED', 'price': 277777,
            'loan_amount': 250000, 'arm_type': '', 'io': '', 'institution': 'BECU',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'KS', 'minfico': 760,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '19': {'maxfico': 715, 'lock': 60, 'rate_structure': 'FIXED', 'price': 200000,
            'loan_amount': 150000, 'arm_type': '', 'io': '', 'institution': '53RD',
            'loan_type': 'VA', 'ltv': 75, 'property_type': '', 'state': 'KY', 'minfico': 715,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '20': {'maxfico': 695, 'lock': 30, 'rate_structure': 'ARM', 'price': 107526,
            'loan_amount': 100000, 'arm_type': '5-1', 'io': '', 'institution': 'REGIONS',
            'loan_type': 'CONF', 'ltv': 93, 'property_type': '', 'state': 'LA', 'minfico': 695,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '21': {'maxfico': 765, 'lock': 45, 'rate_structure': 'ARM', 'price': 533333,
            'loan_amount': 400000, 'arm_type': '10-1', 'io': '', 'institution': 'WEBSTER',
            'loan_type': 'CONF', 'ltv': 75, 'property_type': 'CONDO', 'state': 'MA',
            'minfico': 765, 'loan_term': 30, 'loan_purpose': 'REFI'},
    '22': {'maxfico': 780, 'lock': 60, 'rate_structure': 'ARM', 'price': 687500,
            'loan_amount': 550000, 'arm_type': '7-1', 'io': '', 'institution': 'TDBANK',
            'loan_type': 'AGENCY', 'ltv': 80, 'property_type': '', 'state': 'MD', 'minfico': 780,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '23': {'maxfico': 750, 'lock': 30, 'rate_structure': 'FIXED', 'price': 171428,
            'loan_amount': 120000, 'arm_type': '', 'io': '', 'institution': 'TDBANK',
            'loan_type': 'CONF', 'ltv': 70, 'property_type': '', 'state': 'ME', 'minfico': 750,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '24': {'maxfico': 680, 'lock': 45, 'rate_structure': 'FIXED', 'price': 225000,
            'loan_amount': 180000, 'arm_type': '', 'io': '', 'institution': 'HSBC',
            'loan_type': 'FHA', 'ltv': 80, 'property_type': '', 'state': 'MI', 'minfico': 680,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '25': {'maxfico': 790, 'lock': 60, 'rate_structure': 'ARM', 'price': 470588,
            'loan_amount': 400000, 'arm_type': '10-1', 'io': '',
                'institution': 'CHSCHWAB', 'loan_type': 'CONF', 'ltv': 85,
                'property_type': '', 'state': 'MN', 'minfico': 790, 'loan_term': 30,
                'loan_purpose': 'REFI'},
    '26': {'maxfico': 710, 'lock': 30, 'rate_structure': 'FIXED', 'price': 166666,
            'loan_amount': 150000, 'arm_type': '', 'io': '', 'institution': 'HARRIS',
            'loan_type': 'FHA', 'ltv': 90, 'property_type': '', 'state': 'MO', 'minfico': 710,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '27': {'maxfico': 705, 'lock': 45, 'rate_structure': 'FIXED', 'price': 100000,
            'loan_amount': 80000, 'arm_type': '', 'io': '', 'institution': 'PNC',
            'loan_type': 'CONF', 'ltv': 80, 'property_type': '', 'state': 'MS', 'minfico': 705,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '28': {'maxfico': 740, 'lock': 60, 'rate_structure': 'ARM', 'price': 470588,
            'loan_amount': 400000, 'arm_type': '5-1', 'io': '', 'institution': 'STATEFARM',
            'loan_type': 'CONF', 'ltv': 85, 'property_type': '', 'state': 'MT', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '29': {'maxfico': 690, 'lock': 30, 'rate_structure': 'FIXED', 'price': 368421,
            'loan_amount': 350000, 'arm_type': '', 'io': '', 'institution': 'JPM',
            'loan_type': 'FHA-HB', 'ltv': 95, 'property_type': 'CONDO', 'state': 'NC',
            'minfico': 690, 'loan_term': 30, 'loan_purpose': 'PURCH'},
    '30': {'maxfico': 705, 'lock': 45, 'rate_structure': 'FIXED', 'price': 125625,
            'loan_amount': 100500, 'arm_type': '', 'io': '', 'institution': 'STATEFARM',
            'loan_type': 'CONF', 'ltv': 80, 'property_type': '', 'state': 'ND', 'minfico': 705,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '31': {'maxfico': 710, 'lock': 60, 'rate_structure': 'FIXED', 'price': 259067.35751295337,
            'loan_amount': 250000, 'arm_type': '', 'io': '', 'institution': 'BOFA',
            'loan_type': 'FHA', 'ltv': 96.5, 'property_type': '', 'state': 'NE', 'minfico': 710,
            'loan_term': 15, 'loan_purpose': 'REFI'},
    '32': {'maxfico': 740, 'lock': 30, 'rate_structure': 'FIXED', 'price': 421052,
            'loan_amount': 400000, 'arm_type': '', 'io': '', 'institution': 'SANTANDER',
            'loan_type': 'FHA-HB', 'ltv': 95, 'property_type': '', 'state': 'NH', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '33': {'maxfico': 680, 'lock': 45, 'rate_structure': 'FIXED', 'price': 450000,
            'loan_amount': 450000, 'arm_type': '', 'io': '', 'institution': 'CITI',
            'loan_type': 'VA-HB', 'ltv': 100, 'property_type': '', 'state': 'NJ', 'minfico': 680,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '34': {'maxfico': 720, 'lock': 60, 'rate_structure': 'ARM', 'price': 294117,
            'loan_amount': 250000, 'arm_type': '3-1', 'io': '', 'institution': 'STATEFARM',
            'loan_type': 'CONF', 'ltv': 85, 'property_type': '', 'state': 'NM', 'minfico': 720,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '35': {'maxfico': 745, 'lock': 30, 'rate_structure': 'ARM', 'price': 502409,
            'loan_amount': 417000, 'arm_type': '7-1', 'io': '', 'institution': 'ZIONS',
            'loan_type': 'CONF', 'ltv': 83, 'property_type': '', 'state': 'NV', 'minfico': 745,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '36': {'maxfico': 695, 'lock': 45, 'rate_structure': 'FIXED', 'price': 500000,
            'loan_amount': 400000, 'arm_type': '', 'io': '', 'institution': 'WELLS',
            'loan_type': 'CONF', 'ltv': 80, 'property_type': 'COOP', 'state': 'NY', 'minfico': 695,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '37': {'maxfico': 710, 'lock': 60, 'rate_structure': 'FIXED', 'price': 204081.63265306121,
            'loan_amount': 200000, 'arm_type': '', 'io': '', 'institution': 'HUNTINGTON',
            'loan_type': 'VA', 'ltv': 98.0, 'property_type': '', 'state': 'OH', 'minfico': 710,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '38': {'maxfico': 650, 'lock': 30, 'rate_structure': 'FIXED', 'price': 55555,
            'loan_amount': 50000, 'arm_type': '', 'io': '', 'institution': 'JPM',
            'loan_type': 'FHA', 'ltv': 90, 'property_type': '', 'state': 'OK', 'minfico': 650,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '39': {'maxfico': 730, 'lock': 45, 'rate_structure': 'ARM', 'price': 157894,
            'loan_amount': 150000, 'arm_type': '5-1', 'io': '', 'institution': 'ONPOINT',
            'loan_type': 'CONF', 'ltv': 95, 'property_type': '', 'state': 'OR', 'minfico': 730,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '40': {'maxfico': 725, 'lock': 60, 'rate_structure': 'FIXED', 'price': 294117,
            'loan_amount': 250000, 'arm_type': '', 'io': '', 'institution': 'FIRSTNIAGARA',
            'loan_type': 'FHA', 'ltv': 85, 'property_type': '', 'state': 'PA', 'minfico': 725,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '41': {'maxfico': 690, 'lock': 30, 'rate_structure': 'FIXED', 'price': 315789,
            'loan_amount': 300000, 'arm_type': '', 'io': '', 'institution': 'CHSCHWAB',
            'loan_type': 'FHA-HB', 'ltv': 95, 'property_type': '', 'state': 'RI', 'minfico': 690,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '42': {'maxfico': 780, 'lock': 45, 'rate_structure': 'FIXED', 'price': 750000,
            'loan_amount': 600000, 'arm_type': '', 'io': '', 'institution': 'CAPITAL ONE',
            'loan_type': 'AGENCY', 'ltv': 80, 'property_type': '', 'state': 'SC', 'minfico': 780,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '43': {'maxfico': 750, 'lock': 60, 'rate_structure': 'FIXED', 'price': 66666,
            'loan_amount': 60000, 'arm_type': '', 'io': '', 'institution': 'STATEFARM',
            'loan_type': 'CONF', 'ltv': 90, 'property_type': '', 'state': 'SD', 'minfico': 750,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '44': {'maxfico': 630, 'lock': 30, 'rate_structure': 'FIXED', 'price': 63157,
            'loan_amount': 60000, 'arm_type': '', 'io': '', 'institution': 'RBS',
            'loan_type': 'FHA', 'ltv': 95, 'property_type': '', 'state': 'TN', 'minfico': 630,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '45': {'maxfico': 680, 'lock': 45, 'rate_structure': 'FIXED', 'price': 263157,
            'loan_amount': 250000, 'arm_type': '', 'io': '', 'institution': 'REGIONS',
            'loan_type': 'FHA', 'ltv': 95, 'property_type': '', 'state': 'TX', 'minfico': 680,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '46': {'maxfico': 780, 'lock': 60, 'rate_structure': 'FIXED', 'price': 566666,
            'loan_amount': 425000, 'arm_type': '', 'io': '', 'institution': 'KINECTA',
            'loan_type': 'JUMBO', 'ltv': 75, 'property_type': '', 'state': 'UT', 'minfico': 780,
            'loan_term': 15, 'loan_purpose': 'PURCH'},
    '47': {'maxfico': 710, 'lock': 30, 'rate_structure': 'FIXED', 'price': 605263,
            'loan_amount': 575000, 'arm_type': '', 'io': '', 'institution': 'HSBC',
            'loan_type': 'VA-HB', 'ltv': 95, 'property_type': '', 'state': 'VA', 'minfico': 710,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '48': {'maxfico': 740, 'lock': 45, 'rate_structure': 'FIXED', 'price': 1000000,
            'loan_amount': 800000, 'arm_type': '', 'io': '', 'institution': 'QUICKEN',
            'loan_type': 'JUMBO', 'ltv': 80, 'property_type': '', 'state': 'VT', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '49': {'maxfico': 705, 'lock': 60, 'rate_structure': 'FIXED', 'price': 277777,
            'loan_amount': 250000, 'arm_type': '', 'io': '', 'institution': 'FIRST FEDERAL',
            'loan_type': 'VA', 'ltv': 90, 'property_type': '', 'state': 'WA', 'minfico': 705,
            'loan_term': 15, 'loan_purpose': 'REFI'},
    '50': {'maxfico': 750, 'lock': 30, 'rate_structure': 'ARM', 'price': 368421,
            'loan_amount': 350000, 'arm_type': '10-1', 'io': '', 'institution': 'HARRIS',
            'loan_type': 'CONF', 'ltv': 95, 'property_type': '', 'state': 'WI', 'minfico': 750,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '51': {'maxfico': 790, 'lock': 45, 'rate_structure': 'ARM', 'price': 687500,
            'loan_amount': 550000, 'arm_type': '10-1', 'io': 1.0, 'institution': 'USBANK',
            'loan_type': 'AGENCY', 'ltv': 80, 'property_type': '', 'state': 'WV', 'minfico': 790,
            'loan_term': 30, 'loan_purpose': 'REFI'},
    '52': {'maxfico': 750, 'lock': 60, 'rate_structure': 'ARM', 'price': 588235,
            'loan_amount': 500000, 'arm_type': '5-1', 'io': 1.0, 'institution': 'PNC',
            'loan_type': 'JUMBO', 'ltv': 85, 'property_type': '', 'state': 'WY', 'minfico': 750,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '53': {'maxfico': 740, 'lock': 60, 'rate_structure': 'ARM', 'price': 285714,
            'loan_amount': 200000, 'arm_type': '5-1', 'io': '', 'institution': 'WELLS',
            'loan_type': 'CONF', 'ltv': 70, 'property_type': '', 'state': 'CA', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'PURCH'},
    '54': {'maxfico': 740, 'lock': 60, 'rate_structure': 'FIXED', 'price': 250000,
            'loan_amount': 200000, 'arm_type': '', 'io': '', 'institution': 'BOFA',
            'loan_type': 'CONF', 'ltv': 80, 'property_type': '', 'state': 'CA', 'minfico': 740,
            'loan_term': 30, 'loan_purpose': 'PURCH'}
}


for scenario in test_scenarios.values():
    for k in scenario.keys():
        if '' == scenario[k]:
            del scenario[k]
