# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 16:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratechecker", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="fee", unique_together=set([]),),
        migrations.RemoveField(model_name="fee", name="plan",),
        migrations.DeleteModel(name="Fee",),
    ]
